### ISSUE TITLE
Confirmation: State Doses Data

### ISSUE THREAD

**Issue by aminhusni** [CITF-Malaysia/citf-public#21] opened 2021-07-04 19:42 UTC
Hi, 

Would like to ask if the state data is using PPV's address or the person's address to determine the state?
Just curious since this affects the accuracy of the data.

**Comment by byte** [comment] 2021-07-05 05:51
The answer is currently from what I have read: KL data includes Selangor residents vaccinated at KL centres. This data is supposed to be cleaned up, but we have no idea when this happens.

This is now *crucial* since they're calculating formulas for Phase 2 on a state by state basis, rather than one nation.

Please fix this immediately, I consider this very high value.

More info: https://www.malaymail.com/news/malaysia/2021/07/03/finance-minister-explains-why-and-how-govt-decided-on-phase-two-nrp-shift-f/1986942

**Comment by psyntium** [comment] 2021-07-05 10:48
I think the main question is do `vaxreg_state.csv` and `vax_state.csv` reflects the same source or not?

In other words, if person A registered in Selangor, does vaccination is confirmed in Selangor? because as we know, AZ does not apply to home address anymore.

And does `vaxreg_state.csv` handles double registration accordingly or not.

**Comment by rizalramly** [comment] 2021-07-06 03:19
Hi all,

I also discovered that the data based on PPV location which nilai ambang calculation will be less accurate for at least Klang Valley due to the nature you can get vaccination at PWTC eventhough you stay at Selangor

**Comment by byte** [comment] 2021-07-12 04:06
Periodic reminder to fix this, ASAP. Even the FT Minister is questioning you. https://codeblue.galencentre.org/2021/07/12/annuar-musa-disputes-101-kl-covid-19-vaccination-rate/

**Comment by psyntium** [comment] 2021-07-12 04:55
Most probably the vaccination state is based on location of PPV instead of location of home address.

@CITF-Malaysia please clarify on this. If it is based on PPV address, is it possible to change to user's home address? Or all the info is in silo?

**Comment by byte** [comment] 2021-07-14 06:29
Considering that WP and Selangor is now merged as one, I think this issue can be closed.

**Comment by aminhusni** [comment] 2021-07-14 09:02
> Considering that WP and Selangor is now merged as one, I think this issue can be closed.

The issue covers all states. Not just WP and Selangor. Data accuracy is still in question for all states. 
By all means, anyone can make a representation of the data to be combined like Negeri Sembilan + Melaka but that still does not solve the original issue.

**Comment by aidilsfwn** [comment] 2021-07-20 14:30
Population data not being updated in real-time and a lot of interstate migration are two main contributors. This doesn't just affect the regions within Klang Valley, but the entire country. Could help explain why states like Kelantan and Kedah have lower registration % and the ceiling will be lower than 100%, as a lot of them might have moved to Klang Valley (e.g for jobs) after the latest census was conducted, and have registered for the vaccine in the region they're currently residing in as anyone can choose to get vaccinated anywhere in the country. The only reliable metric we can depend on until this issue is addressed is the population of the country as a whole and its % per population. Things get less accurate as we drill down.

**Comment by CITF-Malaysia** [comment] 2021-07-20 15:42
We are closing this issue for now - the relevant metric to examine (for % coverage) is the number for the entire Klang Valley (Selangor + W.P. Kuala Lumpur + W.P. Putrajaya), due to extremely high mobility between these regions.

Internal analysis suggests this issue is negligible for other states (with respect to @aminhusni 's comment above on Negeri Sembilan / Melaka potentially having similar issues).

Should we publish a different way of looking at the data in future, we will re-open this issue.

**Closed by CITF-Malaysia** 2021-07-20 15:42 UTC

**Comment by cla7632** [comment] 2021-07-22 04:23
> We are closing this issue for now:
> 
> 1. The relevant metric to examine (for % coverage) is the number for the entire Klang Valley (Selangor + W.P. Kuala Lumpur + W.P. Putrajaya), due to extremely high mobility between these regions.
> 2. This high mobility which makes population estimates (based on location of residence) potentially misleading as a denominator also means that the 3 territories should be considered together as an epidemiological unit.
> 3. Internal analysis suggests this issue is negligible for other states (with respect to @aminhusni 's comment above on Negeri Sembilan / Melaka potentially having similar issues).
> 
> Should we publish a different way of looking at the data in future, we will re-open this issue.

registration number is higher than population in KL since 18th Jul 2021. due to point# 1??
![image](https://user-images.githubusercontent.com/86822364/126589541-5e8188e8-8511-4291-bacb-3d3f65c421b4.png)
